include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    deprecated_member_use: ignore
    avoid_print: ignore
    dangling_library_doc_comments: ignore
    dead_null_aware_expression: ignore
    unused_import: ignore
    unreachable_switch_default: ignore
    avoid_web_libraries_in_flutter: ignore
    depend_on_referenced_packages: ignore
  exclude:
    - build/**
    - android/**
    - ios/**
    - windows/**
    - macos/**
