name: geneview_mobile
description: "GENEVIEW Autonomous AI Client"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '^3.5.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0
  audioplayers: ^6.0.0
  flutter_tts: ^4.2.5
  speech_to_text: ^7.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/voice/hu_HU-berta-medium.onnx
    - assets/voice/hu_HU-berta-medium.onnx.json
    - assets/images/
    - assets/images/Geneview.png
    - assets/images/Geneview.jpg
    - assets/images/avatar.jpg
    - assets/data/
    - assets/audio/